apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: flexjar-analytics-demo
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  image: {{image}}
  port: 3000
  replicas:
    min: 1
    max: 2
  liveness:
    path: /api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /api/internal/isReady
    initialDelay: 10
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 256Mi
  ingresses:
    - https://flexjar-analytics-demo.intern.dev.nav.no

  env:
    - name: NODE_ENV
      value: production
    - name: USE_MOCK_DATA
      value: "true"
