apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: flexjar-analytics
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  image: {{image}}
  port: 3000
  replicas:
    min: 2
    max: 4
  liveness:
    path: /api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /api/internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /api/internal/metrics
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  ingresses:
    - https://flexjar-analytics.intern.nav.no
  azure:
    application:
      enabled: true
      allowAllUsers: true
      tenant: nav.no
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - /api/internal/*
  accessPolicy:
    outbound:
      rules:
        - application: flexjar-analytics-api
  env:
    - name: NODE_ENV
      value: production
    - name: FLEXJAR_BACKEND_URL
      value: http://flexjar-analytics-api
    - name: FLEXJAR_BACKEND_AUDIENCE
      value: api://prod-gcp.team-esyfo.flexjar-analytics-api/.default
